# a

In [1]:
#the below code imports numpy and use it to generate random numbers for A,B,C
import numpy as np
A = 80 + 10 * np.random.randn(50)
B = 80 + 10 * np.random.randn(50)
C = 80 + 10 * np.random.randn(50)

In [2]:
#the below code is a function which substracts 10 from each of the grades until the grade is strictly less than 100
def sub_over_100(array):
    for i in range(len(array)):
        if array[i] >= 100:
            array[i]-=10
    return array

In [3]:
#the below code calls the function above for A to get the array of grades for section A
sub_over_100(A)

array([  79.43539742,   83.05300633,   97.3208524 ,   86.1226142 ,
         83.91971482,   87.00862809,   77.63536326,   84.68751006,
         80.01648215,   85.49214673,   87.42451879,   76.18198287,
         63.19752289,   85.09926862,   85.64005958,   71.59576491,
         85.71970205,   69.24169579,   90.2876088 ,   68.45280308,
         88.9687426 ,   83.16734014,   92.3161803 ,   74.37405843,
         69.61255972,   83.59684793,   58.18695897,   77.64438066,
         80.67649339,   76.86133076,   63.48330249,   70.23354861,
         80.23787928,   93.05329826,   76.48418681,   96.79388604,
         97.43929043,   71.33507414,   98.0428723 ,   98.12521843,
         72.58320319,   67.57152982,   87.66978105,   76.85258306,
         81.64693457,   71.8152376 ,   75.98129077,   91.01315222,
         85.06670523,  100.77144933])

In [4]:
#the below code calls the function above for B to get the array of grades for section B
sub_over_100(B)

array([ 90.44536553,  75.27753731,  76.22072332,  89.07158121,
        94.67645374,  90.81910717,  80.90854821,  90.61000914,
        87.67184993,  79.6072289 ,  86.77759229,  82.12646999,
        73.48930678,  77.35471036,  80.86048073,  91.97096258,
        81.6546219 ,  87.26782806,  88.8561267 ,  63.24023792,
        74.59157166,  70.06037809,  74.06158778,  65.00012659,
        82.67754664,  76.80199709,  93.17920662,  64.82712367,
        72.23411456,  86.43913586,  72.62184731,  85.75030276,
        55.85410984,  76.33546426,  70.56019965,  67.37451328,
        80.29766203,  96.34508109,  86.37989574,  70.84369911,
        82.69458661,  85.99030141,  74.61409675,  75.64936727,
        93.83870681,  76.44756322,  70.82031999,  61.36675396,
        67.77609061,  76.43824559])

In [5]:
#the below code calls the function above for C to get the array of grades for section C
sub_over_100(C)

array([ 89.33816455,  76.26629827,  77.37968968,  89.83142074,
        83.95465048,  87.65187401,  97.58454316,  84.93543435,
        66.01876311,  69.87348275,  78.80228716,  78.88668838,
        93.4123084 ,  85.95616876,  83.42350886,  77.22308229,
        83.84989742,  73.89198251,  82.56621076,  97.69214141,
        84.12168594,  84.51215344,  71.0513109 ,  90.86798269,
        84.27145823,  69.24926574,  86.91184072,  73.61107107,
        88.3601449 ,  91.88746986,  91.12555521,  84.55702781,
        97.19878451,  94.02253259,  78.75210898,  74.61680351,
        82.74276562,  88.68768114,  77.80546361,  88.47321765,
        82.42382301,  73.00236354,  74.13021166,  84.63085415,
        77.56603259,  77.89884838,  75.53683204,  93.25077707,
        73.89312207,  71.9462618 ])

# b

In [6]:
#Concatenates the grades into a single 1-D array "Result" and shows the result
temp=np.concatenate((A,B),axis=0)
Result=np.concatenate((temp,C),axis=0)
Result

array([  79.43539742,   83.05300633,   97.3208524 ,   86.1226142 ,
         83.91971482,   87.00862809,   77.63536326,   84.68751006,
         80.01648215,   85.49214673,   87.42451879,   76.18198287,
         63.19752289,   85.09926862,   85.64005958,   71.59576491,
         85.71970205,   69.24169579,   90.2876088 ,   68.45280308,
         88.9687426 ,   83.16734014,   92.3161803 ,   74.37405843,
         69.61255972,   83.59684793,   58.18695897,   77.64438066,
         80.67649339,   76.86133076,   63.48330249,   70.23354861,
         80.23787928,   93.05329826,   76.48418681,   96.79388604,
         97.43929043,   71.33507414,   98.0428723 ,   98.12521843,
         72.58320319,   67.57152982,   87.66978105,   76.85258306,
         81.64693457,   71.8152376 ,   75.98129077,   91.01315222,
         85.06670523,  100.77144933,   90.44536553,   75.27753731,
         76.22072332,   89.07158121,   94.67645374,   90.81910717,
         80.90854821,   90.61000914,   87.67184993,   79.60722

# c

In [7]:
#Calculates the mean (m) and standard deviation (sd) of the single array and print the results.
m=np.mean(Result)
print("The mean is",m)
sd=np.std(Result)
print("The standard deviation is",sd)

The mean is 81.0104022965
The standard deviation is 9.24846374876


# d

In [8]:
#Normalizes the single array "Result" by subtracting the mean m from each grade and dividing by the standard deviation sd
for i in range(len(Result)):
    Result[i]-=m
    Result[i]/=sd
Result

array([-0.17029908,  0.22085874,  1.7635848 ,  0.55276336,  0.31457252,
        0.64856456, -0.36492969,  0.3975912 , -0.10746868,  0.48459339,
        0.69353318, -0.522078  , -1.92603657,  0.44211303,  0.50058663,
       -1.0179677 ,  0.50919806, -1.27250393,  1.00310784, -1.3578038 ,
        0.86050403,  0.2332212 ,  1.2224493 , -0.71756175, -1.23240388,
        0.27966219, -2.46780914, -0.36395468, -0.03610426, -0.44862278,
       -1.89513635, -1.16525879, -0.08352987,  1.30215096, -0.48940187,
        1.706606  ,  1.77639104, -1.04615517,  1.84165397,  1.85055774,
       -0.91119989, -1.45309241,  0.72005243, -0.44956864,  0.06882573,
       -0.99423698, -0.54377804,  1.081558  ,  0.43859208,  2.13668427,
        1.02016546, -0.61987214, -0.51788914,  0.87162356,  1.47765638,
        1.06057667, -0.01101308,  1.03796772,  0.72027612, -0.15171962,
        0.62358356,  0.12067601, -0.81322647, -0.39527559, -0.01621043,
        1.18512226,  0.06965693,  0.67659083,  0.84832731, -1.92

# e

In [9]:
#The below code implements the below mentioned grading scheme and prints the report
#Grading Scheme
#    grade<-2-->F
#-2<=grade<-1-->D
#-1<=grade<0-->C
# 0<=grade<1-->B
#   grade>=1-->A
A=[]
B=[]
C=[]
D=[]
F=[]

for i in range(len(Result)):
    if Result[i] < -2:
        F.append(Result[i])
    elif Result[i] >= -2 and Result[i]<-1:
        D.append(Result[i])
    elif Result[i] >= -1 and Result[i]<0:
        C.append(Result[i])
    elif Result[i] >= 0 and Result[i]<1:
        B.append(Result[i])
    elif Result[i] >= 1:
        A.append(Result[i])
print("\n\nThe Report of number of Students who received each grade")
print("The number of students who received A are",len(A))
print("The number of students who received B are",len(B))
print("The number of students who received C are",len(C))
print("The number of students who received D are",len(D))
print("The number of students who received F are",len(F))



The Report of number of Students who received each grade
The number of students who received A are 27
The number of students who received B are 49
The number of students who received C are 49
The number of students who received D are 22
The number of students who received F are 3
